name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build_user_service:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.20'

      - name: Set up Secrets for User Service
        env:
          DB_USER: ${{ secrets.DB_USER }}
          DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
        run: |
          echo "DB_USER=${DB_USER}" > .env
          echo "DB_PASSWORD=${DB_PASSWORD}" >> .env

      - name: Build and Push User Service Docker Image
        run: |
          docker build -t paulodhiambo/userservice:latest ./userservice
#          docker login -u ${{ secrets.DOCKERHUB_USERNAME }} -p ${{ secrets.DOCKERHUB_TOKEN }}
#          docker push your-docker-username/user-service:latest
